#!/bin/bash

# autostart in ~/.bash_profile

# dependencies: omxplayer mediainfo timelimit

MAXSECONDS=30 # maximum duration of clip

sudo mount -t exfat -o ro /dev/sda1 /media/usb
FOLDER="/media/usb/videodrome"

while true; do # infinite loop

	pkill omxplayer # kill omxplayer if it is still active (somehow 'timelimit' does not do this)

	FILE=$( find "$FOLDER/" -type f -print0 | shuf -z -n 1 ) # pick random file
	clear # clear screen

	LENGTH="$(mediainfo --Inform="Video;%Duration%" $FILE)" # length is in ms
	if [ -z "$LENGTH" ]; then # cannot get length; just assume 60 seconds
		LENGTH=60000
	fi
	((LENGTH=${LENGTH}/1000)) # convert to seconds
	((MAXPOS=$LENGTH - 5))
	((RANDOMPOS="$(shuf -i 0-$MAXPOS -n 1)")) # get a random position between 0 and $MAXPOS
	((h=$RANDOMPOS/3600))
	((m=($RANDOMPOS%3600)/60))
	((s=$RANDOMPOS%60))
	RANDOMPOSOMX="$(printf "%02d:%02d:%02d" $h $m $s)" # convert to hh:mm:ss
	((RANDOMLENGTH="$(shuf -i 0-$MAXSECONDS -n 1)"))
	timelimit -t $RANDOMLENGTH -T $RANDOMLENGTH -q omxplayer --pos $RANDOMPOSOMX --no-osd $FILE > /dev/null

done

